### ISSUE TITLE
main.py field -o v should not always require the eta file to exist

### ISSUE THREAD

**Issue by labrosse** [mulvrova/StagPy#6]
In case with a constant viscosity it should not try to open the viscosity file. It can be checked by looking at the par file if it exists. Or as a boolean argument.

**Comment by amorison** [comment]
With -o v, you were actually unintentionally asking stagpy to plot the viscosity since "v" currently refers to "viscosity" (I'll change that, it's indeed poorly chosen) . There is no option to plot the velocity field yet, there is only the stream function for the moment.

**Comment by amorison** [comment]
Done. `n` refers to the viscosity instead of `v`.

**Comment by labrosse** [comment]
Cool !
